YuksekAtes/YuksekAtesBlog/YuksekAtesBlog.WebUI/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using YuksekAtesBlog.Business.Services;
using YuksekAtesBlog.Data.Dto;
using YuksekAtesBlog.WebUI.Areas.Admin.Models;

namespace YuksekAtesBlog.WebUI.Areas.Admin.Controllers
{
    public class CategoryController : BaseController
    {
        private readonly ICategoryService _categoryService;
        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public IActionResult Index()
        {
            var categoryList = _categoryService.GetCategories();

            var viewModel = categoryList.Select(x => new CategoryViewModel
            {
                Id = x.Id,
                Name = x.Name,
            }).ToList();

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult New()
        {
            return View("Form", new CategoryFormViewModel());
        }

        [HttpPost]
        public IActionResult Save(CategoryFormViewModel formdata)
        {
            if (!ModelState.IsValid)
            {
                return View("Form", formdata);
            }

            var categoryDto = new CategoryDto
            {
                Id = formdata.Id,
                Name = formdata.Name,
            };

            if (formdata.Id == 0)
            {

                var response = _categoryService.AddCategory(categoryDto);

                if (response.IsSucceed)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.ErrorMessage = response.Message;
                    return View("form", formdata);
                }
            }
            else
            {
                _categoryService.EditCategory(categoryDto);

                return RedirectToAction("Index");
            }
        }

        public IActionResult Edit(int id)
        {
            var category = _categoryService.GetCategoryById(id);

            var viewModel = new CategoryFormViewModel()
            {
                Id = category.Id,
                Name = category.Name,
            };

            return View("Form", viewModel);
        }

        public IActionResult Delete(int id)
        {
            _categoryService.DeleteCategory(id);
            return RedirectToAction("Index");
        }
    }
}

YuksekAtes/YuksekAtesBlog/YuksekAtesBlog.WebUI/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace YuksekAtesBlog.WebUI.Areas.Admin.Controllers
{
    public class DashboardController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

YuksekAtes/YuksekAtesBlog/YuksekAtesBlog.WebUI/Areas/Admin/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using YuksekAtesBlog.Business.Services;
using YuksekAtesBlog.Data.Dto;
using YuksekAtesBlog.WebUI.Areas.Admin.Models;

namespace YuksekAtesBlog.WebUI.Areas.Admin.Controllers
{
    public class PostController : BaseController
    {
        private readonly ICategoryService _categoryService;
        private readonly IPostService _postService;
        private readonly IWebHostEnvironment _environment;
        public PostController(ICategoryService categoryService, IPostService postService, IWebHostEnvironment environment)
        {
            _categoryService = categoryService;
            _postService = postService;
            _environment = environment;
        }

        public IActionResult Index()
        {
            var postList = _postService.GetAll();

            var viewModel = postList.Select(x => new PostViewModel
            {
                Id = x.Id,
                Name = x.Name,
                Description = x.Description,
                Summary = x.Summary,
                ImagePath = x.ImagePath,
                CategoryId = x.CategoryId,
                CategoryName = x.CategoryName

            }).ToList();

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult New()
        {
            var categories = _categoryService.GetCategories();
            ViewBag.Categories = categories;

            return View("Form", new PostFormViewModel());
        }

        [HttpPost]
        public IActionResult Save(PostFormViewModel formdata)
        {
            if (!ModelState.IsValid)
            {
                var categories = _categoryService.GetCategories();
                ViewBag.Categories = categories;

                return View("Form", formdata);
            }

            var allowedFileContentTypes = new string[] { "image/jpeg", "image/jpg", "image/png", "image/jfif" };
            var allowedFileExtensions = new string[] { ".jpeg", ".jpg", "png", ".jfif" };

            var fileContentType = formdata.File.ContentType;
            var fileNameWithoutExtensions = Path.GetFileNameWithoutExtension(formdata.File.FileName);
            var fileExtension = Path.GetExtension(formdata.File.FileName);

            if (formdata.File == null || formdata.File.Length == 0 ||
                !allowedFileContentTypes.Contains(fileContentType) ||
                !allowedFileExtensions.Contains(fileExtension))
            {
                ModelState.AddModelError("file", "Lütfen jpg, jpeg, jfif veya png Tipinde Geçerli Bir Dosya Yükleyiniz.");

                var categories = _categoryService.GetCategories();
                ViewBag.Categories = categories;

                return View("Form", formdata);
            }

            var newFileName = fileNameWithoutExtensions + "_" + Guid.NewGuid() + fileExtension;
            var folderPath = Path.Combine("images", "posts");
            var wwwRootFolderPath = Path.Combine(_environment.WebRootPath, folderPath);
            var wwwRootFilePath = Path.Combine(wwwRootFolderPath, newFileName);

            Directory.CreateDirectory(wwwRootFolderPath);

            using (var fileStream = new FileStream(wwwRootFilePath, FileMode.Create))
            {
                formdata.File.CopyTo(fileStream);
            }


            if (formdata.Id == 0)
            {
                var postDto = new PostDto
                {
                    Id = formdata.Id,
                    Name = formdata.Name,
                    Description = formdata.Description,
                    Summary = formdata.Summary,
                    ImagePath = newFileName,
                    CategoryId = formdata.CategoryId
                };

                var response = _postService.AddPost(postDto);

                if (response.IsSucceed)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    var categories = _categoryService.GetCategories();
                    ViewBag.Categories = categories;

                    ViewBag.ErrorMessage = response.Message;
                    return View("form", formdata);
                }
            }
            else
            {
                var postDto = new PostDto
                {
                    Id = formdata.Id,
                    Name = formdata.Name,
                    Description = formdata.Description,
                    Summary = formdata.Summary,
                    ImagePath = newFileName,
                    CategoryId = formdata.CategoryId
                };
                if (formdata.File != null)
                {
                    postDto.ImagePath = newFileName;
                }
                _postService.EditPost(postDto);

            }
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            var categories = _categoryService.GetCategories();
            ViewBag.Categories = categories;
            var post = _postService.GetPostById(id);

            var viewModel = new PostFormViewModel()
            {
                Id = post.Id,
                Description = post.Description,
                Name = post.Name,
                Summary = post.Summary,
                CategoryId = post.CategoryId,
            };

            ViewBag.Image = post.ImagePath;

            return View("Form", viewModel);
        }

        public IActionResult Delete(int id)
        {
            _postService.DeletePost(id);
            return RedirectToAction("Index");
        }
    }
}

YuksekAtes/YuksekAtesBlog/YuksekAtesBlog.WebUI/Areas/Admin/Views/Shared/_CssPartial.cshtml
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />

<link href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" rel="stylesheet" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.20/summernote-bs4.min.css" integrity="sha512-ngQ4IGzHQ3s/Hh8kMyG4FC74wzitukRMIcTOoKT3EyzFZCILOPF0twiXOQn75eDINUfKBYmzYn2AA8DkAk8veQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/css/lightbox.min.css" integrity="sha512-ZKX+BvQihRJPA8CROKBhDNvoc2aDMOdAlcm7TUQY+35XYtrd3yh95QOOhsPDQY9QnKE0Wqag9y38OIgEvb88cA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.4.29/sweetalert2.min.css" integrity="sha512-doewDSLNwoD1ZCdA1D1LXbbdNlI4uZv7vICMrzxfshHmzzyFNhajLEgH/uigrbOi8ETIftUGBkyLnbyDOU5rpA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

YuksekAtes/YuksekAtesBlog/YuksekAtesBlog.WebUI/Areas/Admin/Views/Shared/_JsPartial.cshtml
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js" integrity="sha512-rstIgDs0xPgmG6RX1Aba4KV5cWJbAMcvRCVmglpam9SoHZiUCyQVDdH2LPlxoHtrv17XWblE/V/PP+Tr04hbtA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/4.0.0/jquery.validate.unobtrusive.min.js" integrity="sha512-xq+Vm8jC94ynOikewaQXMEkJIOBp7iArs3IhFWSWdRT3Pq8wFz46p+ZDFAR7kHnSFf+zUv52B3prRYnbDRdgog==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.20/summernote.min.js" integrity="sha512-6rE6Bx6fCBpRXG/FWpQmvguMWDLWMQjPycXMr35Zx/HRD9nwySZswkkLksgyQcvrpYMx0FELLJVBvWFtubZhDQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/js/lightbox.min.js" integrity="sha512-k2GFCTbp9rQU412BStrcD/rlwv1PYec9SNrkbQlo6RZCf75l6KcC3UwDY8H5n5hl4v77IDtIPwOk9Dqjs/mMBQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.4.29/sweetalert2.min.js" integrity="sha512-gCB2+0sWe4La5U90EqaPP2t58EczKkQE9UoCpnkG2EDSOOihgX/6MiT3MC4jYVEX03pv6Ydk1xybLG/AtN+3KQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

  <script>
        $(document).ready(function () {
            $('.summernote').summernote();
        });
    </script>

YuksekAtes/YuksekAtesBlog/YuksekAtesBlog.WebUI/Areas/Admin/Views/Shared/_Layout.cshtml
<html>
<head>
    <title>Yüksek Ateş Blog</title>

    <partial name="_CssPartial"></partial>

    <style>
        label.required:after {
            content: "*\00a0";
            color: red;
            margin-left: 2px;
        }
    </style>

</head>

<body class="d-flex flex-column min-vh-100">

    <header class="p-3 text-bg-dark">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a asp-area="Admin" asp-controller="Dashboard" asp-action="Index" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none fw-bold">
                    YÜKSEK ATEŞ YÖNETİM PANELİ
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0 ms-5">        
                    <li><a asp-area="Admin" asp-controller="Category" asp-action="Index" class="nav-link px-2 text-white">Kategoriler</a></li>
                    <li><a asp-area="Admin" asp-controller="Post" asp-action="Index" class="nav-link px-2 text-white">İçerikler</a></li>
                    <li><a asp-area="Admin" asp-controller="Account" asp-action="AccountUpdate" class="nav-link px-2 text-white">Şifre Güncelle</a></li>
                </ul>

                <div class="ms-3 text-white mt-1">
                    <a class="btn btn-secondary" asp-area="" asp-controller="Home" asp-action="Index">Ana Sayfa</a>
                </div>

            </div>
        </div>
    </header>


    @RenderBody()

    <footer class="py-5 bg-dark text-white text-center mt-3 mt-auto">
        Yüksek Ateş | 2022
    </footer>

    <partial name="_JsPartial"></partial>

    @await RenderSectionAsync("Scripts", required:false);
    @await RenderSectionAsync("Update" , required: false)

    <script>
        $(document).ready(function () {
            $('.summernote').summernote();
        });
    </script>

</body>
</html>